#!/bin/sh
function v2g() {
  ffmpeg -i "$1" -pix_fmt rgb8 -r 10 "$2" && gifsicle -O3 "$2" -o "$2"
}

# force env vars that are updated in tmux session to update in pane
function tmup() {
  eval $(tmux showenv -s)
  echo "🤘tmux env reloaded..."
}

function jme() {
  jira issue list -a $(jira me) -s~Done --columns TYPE,KEY,SUMMARY,STATUS,PRIORITY,LABELS
}

function ji() {
  jira issue view "$1"
}

function jo() {
  jira open "$1"
}

function jc() {
  jira issue list -a $(jira me) -s 'In Progress' --paginate 1 --plain --no-headers --columns KEY | tr -d '\n'
}

function jcy() {
  echo '📂 copying in progress item to clipboard...'
  jira issue list -a $(jira me) -s 'In Progress' --paginate 1 --plain --no-headers --columns KEY | tr -d '\n' | pbcopy
  echo $(pbpaste)
}
