for file in ~/.dotfiles/shell/{aliases,functions,prompt,completions,directories}; do
  [ -r "$file" ] && source "$file"
done
unset file

export EDITOR="nvim"
export SHELL="zsh"
export LANG="en_US.UTF-8"
export CLICOLOR=1
export CHROME_PATH=/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser

# history file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000

# set path for homebrew
eval "$(/opt/homebrew/bin/brew shellenv)" 

# Use emacs key bindings
bindkey -e
# make delete key delete
bindkey "^[[3~" delete-char

bindkey -s ^t "^utmux-sessionizer\n"
bindkey -s ^g "^urepome\n"

source $HOMEBREW_PREFIX/opt/zsh-fast-syntax-highlighting/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export PATH="$(yarn global bin):$PATH"
export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"

# my bin
export PATH=$PATH:~/.dotfiles/bin

# Add the following to your shell init to set up gpg-agent automatically for every shell
if ! [ -n "$(pgrep gpg-agent)" ]; then
  eval $(gpg-agent --daemon)
fi

export FZF_DEFAULT_COMMAND='fd --type file'
export FZF_DEFAULT_OPTS="--ansi --color 16"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

. "$HOME/.asdf/asdf.sh"

# local settings
source $HOME/.zshrc.local

pokemon-colorscripts -r
