export EDITOR="nvim"
export SHELL="/bin/zsh"
export LANG="en_US.UTF-8"
export CLICOLOR=1

# history file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000

# set path for homebrew
eval "$(/opt/homebrew/bin/brew shellenv)" 

for file in ~/.dotfiles/shell/{aliases,functions,completions,directories}; do
  [ -r "$file" ] && source "$file"
done
unset file

# prompt
eval "$(starship init zsh)"

# Use emacs key bindings
bindkey -e
# make delete key delete
bindkey "^[[3~" delete-char

# bindkey -s ^t "^utmux-sessionizer\n"
bindkey -s ^g "^urepome\n"

source $HOMEBREW_PREFIX/opt/zsh-fast-syntax-highlighting/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export PATH="$(yarn global bin):$PATH"

export PATH="/Users/john/Library/Android/sdk/platform-tools:$PATH"

export PATH="$HOMEBREW_PREFIX/opt/libpq/bin:$PATH"

export PATH="/opt/webOS_Signage_SDK/CLI/bin:$PATH"

export PATH="/Users/john/tizen-studio/tools:$PATH"
export PATH="/Users/john/tizen-studio/tools/ide/bin:$PATH"

# my bin
export PATH=$PATH:~/.dotfiles/bin

# rust bin
export PATH=$PATH:~/.cargo/bin

# Add the following to your shell init to set up gpg-agent automatically for every shell
if ! [ -n "$(pgrep gpg-agent)" ]; then
  eval $(gpg-agent --daemon)
fi

export FZF_DEFAULT_COMMAND='fd --type file'
export FZF_DEFAULT_OPTS="--ansi --color 16"
source $HOMEBREW_PREFIX/opt/fzf/shell/completion.zsh

export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

eval "$(atuin init zsh --disable-up-arrow)"

eval "$(colima completion zsh)"

# bun completions
[ -s "/Users/john/.bun/_bun" ] && source "/Users/john/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# local settings
source $HOME/.zshrc.local

pokemon-colorscripts -r
