for file in ~/.{aliases,functions,keys,prompt}; do
  [ -r "$file" ] && source "$file"
done
unset file

export EDITOR="nvim"
export SHELL="zsh"
export LANG="en_US.UTF-8"
export CLICOLOR=1
export CHROME_PATH=/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser

# set path for homebrew
eval "$(/opt/homebrew/bin/brew shellenv)" 

source ~/.dotfiles/shell/completions
source ~/.dotfiles/shell/directories

# Use emacs key bindings
bindkey -e

source $HOMEBREW_PREFIX/opt/zsh-fast-syntax-highlighting/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$(yarn global bin):$PATH"
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin

# added by travis gem
[ -f /Users/john.pinkerton/.travis/travis.sh ] && source /Users/john.pinkerton/.travis/travis.sh

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# go bin path
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# my bin
export PATH=$PATH:~/.dotfiles/bin

# Add the following to your shell init to set up gpg-agent automatically for every shell
if ! [ -n "$(pgrep gpg-agent)" ]; then
  eval $(gpg-agent --daemon)
fi

eval "`fnm env --use-on-cd`"

export FZF_DEFAULT_COMMAND='fd --type file'
export FZF_DEFAULT_OPTS="--ansi"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

function v2g() {
  ffmpeg -i "$1" -pix_fmt rgb8 -r 10 "$2" && gifsicle -O3 "$2" -o "$2"
}

# local settings
source $HOME/.zshrc.local
