return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  lazy = false,
  dependencies = { 'OXY2DEV/markview.nvim' },
  opts = {
    ensure_installed = {
      'bash',
      'css',
      'dockerfile',
      'embedded_template',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'graphql',
      'hcl',
      'helm',
      'html',
      'java',
      'javascript',
      'json',
      'latex',
      'make',
      'markdown',
      'markdown_inline',
      'prisma',
      'python',
      'regex',
      'ruby',
      'rust',
      'ssh_config',
      'sql',
      'terraform',
      'tsx',
      'typescript',
      'yaml',
      'xml',
      -- these are required since neovim 0.8
      'c',
      'lua',
      'vim',
      'vimdoc',
    },
    highlight = {
      enable = true,
    },
    indent = {
      enable = true,
    },
  },
  config = function(_, opts)
    require('nvim-treesitter.configs').setup(opts)
  end,
}
